/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "ClearlyDefined Docs",
  "tagline": "Helping Open Source projects be more successful through clearly defined licensing data",
  "favicon": "img/favicon.ico",
  "url": "https://docs.clearlydefined.io",
  "baseUrl": "/",
  "organizationName": "clearlydefined",
  "projectName": "clearlydefined",
  "deploymentBranch": "gh-pages",
  "trailingSlash": false,
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.js",
          "editUrl": "https://github.com/clearlydefined/clearlydefined"
        },
        "blog": {
          "showReadingTime": true,
          "editUrl": "https://github.com/clearlydefined/clearlydefined"
        },
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/ClearlyDefined-social-card.jpg",
    "navbar": {
      "title": "",
      "logo": {
        "alt": "ClearlyDefined",
        "src": "img/clearlydefined.svg"
      },
      "items": [
        {
          "type": "dropdown",
          "label": "Docs",
          "to": "/docs/get-involved/intro",
          "position": "left",
          "items": [
            {
              "label": "Introduction",
              "to": "/docs/get-involved/intro"
            },
            {
              "label": "Use the data",
              "to": "/docs/get-involved/using-data"
            },
            {
              "label": "Curate the data",
              "to": "/docs/get-involved/data-curation"
            },
            {
              "label": "Contribute data",
              "to": "/docs/get-involved/contributing-data"
            },
            {
              "label": "Contribute code",
              "to": "/docs/get-involved/contributing-code"
            },
            {
              "label": "Add a harvest",
              "to": "/docs/get-involved/adding-sources"
            },
            {
              "label": "Adopt practices",
              "to": "/docs/get-involved/adopting"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Resources",
          "to": "/docs/get-involved/intro",
          "position": "left",
          "items": [
            {
              "label": "Blog",
              "href": "/blog"
            },
            {
              "label": "FAQ",
              "href": "/docs/resources/faq"
            },
            {
              "label": "Glossary",
              "href": "/docs/resources/glossary"
            },
            {
              "label": "Providers",
              "href": "/docs/resources/providers"
            },
            {
              "label": "Curation",
              "href": "/docs/curation/curation-guidelines"
            },
            {
              "label": "Harvest",
              "href": "/docs/harvest/intro"
            },
            {
              "label": "Roadmap",
              "href": "/docs/resources/roadmap"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Community",
          "to": "/docs/get-involved/intro",
          "position": "left",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/clearlydefined"
            },
            {
              "label": "Forum",
              "to": "https://discord.gg/wEzHJku"
            },
            {
              "label": "Events",
              "to": "/docs/community/events"
            },
            {
              "label": "Meetings",
              "to": "/docs/community/meetings"
            },
            {
              "label": "Members",
              "to": "/docs/community/members"
            },
            {
              "label": "Code of Conduct",
              "to": "/docs/community/coc"
            },
            {
              "label": "Charter",
              "to": "/docs/community/charter"
            }
          ]
        },
        {
          "href": "https://github.com/clearlydefined",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Introduction",
              "to": "/docs/get-involved/intro"
            },
            {
              "label": "Use the data",
              "to": "/docs/get-involved/using-data"
            },
            {
              "label": "Curate the data",
              "to": "/docs/get-involved/data-curation"
            },
            {
              "label": "Contribute data",
              "to": "/docs/get-involved/contributing-data"
            },
            {
              "label": "Contribute code",
              "to": "/docs/get-involved/contributing-code"
            },
            {
              "label": "Add a harvest",
              "to": "/docs/get-involved/adding-sources"
            },
            {
              "label": "Adopt practices",
              "to": "/docs/get-involved/adopting"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Blog",
              "href": "/blog"
            },
            {
              "label": "FAQ",
              "href": "/docs/resources/faq"
            },
            {
              "label": "Glossary",
              "href": "/docs/resources/glossary"
            },
            {
              "label": "Providers",
              "href": "/docs/resources/providers"
            },
            {
              "label": "Curation",
              "href": "/docs/curation/curation-guidelines"
            },
            {
              "label": "Harvest",
              "href": "/docs/harvest/intro"
            },
            {
              "label": "Roadmap",
              "href": "/docs/resources/roadmap"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/clearlydefined"
            },
            {
              "label": "Forum",
              "to": "https://discord.gg/wEzHJku"
            },
            {
              "label": "Events",
              "to": "/docs/community/events"
            },
            {
              "label": "Meetings",
              "to": "/docs/community/meetings"
            },
            {
              "label": "Members",
              "to": "/docs/community/members"
            },
            {
              "label": "Code of Conduct",
              "to": "/docs/community/coc"
            },
            {
              "label": "Charter",
              "to": "/docs/community/charter"
            }
          ]
        }
      ]
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
